# There's different naming conventions we can use here, let's agree to use
# nouns that best represent the work flow so ex. Unit Test not Run Unit Tests
name: Development Checks
on:
  push:
    # This is saying: only test against pushes to these three branches, and ignore
    # All tag creations (also considered a push)
    branches:
      - master
      - main
      - development
    tags-ignore:
      - '**'
  pull_request:


permissions:
  packages: read

jobs:
  run-unit-tests:
    if: ${{ !contains(github.event.pull_request.labels.*.name, 'wip') }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    env:
      GITHUB_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js LTS version
        uses: actions/setup-node@v3
        with:
          # this defaults to using nvms latest version, which we should be
          # following, however we can be more specific (ex. '16.x')
          node-version: 'lts/*'
      - name: Copy .npmrc.example to .npmrc
        run: 'rm -rf .npmrc && cp .npmrc.example .npmrc'
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Run build
        run: yarn build
      - name: Run unit tests
        run: yarn test
