name: run-unit-tests
on:
  push:
  pull_request:
    # See: https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#running-your-workflow-based-on-files-changed-in-a-pull-request
    paths:
      - '**.ts'
      - '**.tsx'

jobs:
  run-unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js LTS version
        uses: actions/setup-node@v3
        with:
          # this defaults to using nvms latest version, which we should be
          # following, however we can be more specific (ex. '16.x')
          node-version: 'lts/*'
      - run: yarn install --frozen-lockfile
      - run: yarn test
